/**
 * Copyright (c) 2015 Zenika
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Mario Loriedo @mariolet - Initial implementation
 */
/*
 * generated by Xtext
 */
package com.zenika.docker.dsl.ui;

import static com.zenika.docker.dsl.ui.XtextSetup.configureXtextToWorkWithFileNames;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DockerfileDslUiModule extends com.zenika.docker.dsl.ui.AbstractDockerfileDslUiModule {
	public DockerfileDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		configureXtextToWorkWithFileNames(new InjectorProvider());
	}
}
