/*
 * generated by Xtext
 */
package com.zenika.docker.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDockerfileDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.zenika.docker.dsl.dockerfileDsl.DockerfileDslPackage.eINSTANCE);
		return result;
	}
}
