/*
 * generated by Xtext
 */
package com.zenika.docker.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DockerfileDslRuntimeModule extends com.zenika.docker.dsl.AbstractDockerfileDslRuntimeModule {

}
