/*
 * generated by Xtext
 */
package com.zenika.docker.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.zenika.docker.dsl.ui.internal.DockerfileDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DockerfileDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DockerfileDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DockerfileDslActivator.getInstance().getInjector(DockerfileDslActivator.COM_ZENIKA_DOCKER_DSL_DOCKERFILEDSL);
	}
	
}
