/**
 * generated by Xtext
 */
package com.zenika.docker.dsl.validation;

import com.zenika.docker.dsl.validation.AbstractDockerfileDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DockerfileDslValidator extends AbstractDockerfileDslValidator {
}
