/*
 * generated by Xtext
 */
package com.zenika.doclipser.dsl.ui.contentassist

import com.zenika.doclipser.dsl.ui.contentassist.AbstractDockerfileDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DockerfileDslProposalProvider extends AbstractDockerfileDslProposalProvider {
}
