/*
* generated by Xtext
*/
package com.zenika.docker.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.zenika.docker.dsl.services.DockerfileDslGrammarAccess;

public class DockerfileDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DockerfileDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.zenika.docker.dsl.parser.antlr.internal.InternalDockerfileDslParser createParser(XtextTokenStream stream) {
		return new com.zenika.docker.dsl.parser.antlr.internal.InternalDockerfileDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Dockerfile";
	}
	
	public DockerfileDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DockerfileDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
