/*
* generated by Xtext
*/
package com.zenika.docker.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DockerfileDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/zenika/docker/dsl/parser/antlr/internal/InternalDockerfileDsl.tokens");
	}
}
