/**
 * generated by Xtext
 */
package com.zenika.docker.dsl.ui.contentassist;

import com.zenika.docker.dsl.ui.contentassist.AbstractDockerfileDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DockerfileDslProposalProvider extends AbstractDockerfileDslProposalProvider {
}
