/**
 * Copyright (c) 2015 Zenika
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Mario Loriedo @mariolet - Initial implementation
 */
/*
* generated by Xtext
*/
package com.zenika.doclipser.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DockerfileDslStandaloneSetup extends DockerfileDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DockerfileDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

